env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=NRCrdmKG7DLyHJfbGEUfcBsv7uMCs4U13

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
